---
  - name: Configuration for Lisk with Ansible
    hosts: all
    become: True
    vars:
      - nodejs_version: "4.x"
      - nodejs_npm_global_packages:
        - name: forever
      - mongodb_net_bindip: 0.0.0.0
    roles:
      - python
      - node
      # - geerlingguy.nodejs
      - lisk
      - pgsql
      - greendayonfire.mongodb
    tasks:
      - name: locale
        locale_gen: name=en_US.UTF-8 state=present
      - name: dev locale
        action: command sudo update-locale LC_ALL=en_US.UTF-8
      - name: set default locale
        become: yes
        lineinfile: dest=/etc/default/locale
          regexp="LC_ALL"
          line="LC_ALL=\"en_US.UTF-8\""
