---
- name: install essentials
  apt: name=build-essential state=latest
- name: install python setuptools
  apt: name=python-setuptools state=latest
- name: install python-dev
  apt: name=python-dev state=latest
- name: installing python req
  become: True
  apt: name=python-pip state=latest
- name: installing the req pkg
  become: True
  pip: name=pexpect state=latest
