---
# tasks file for lisk

- name: Make sure the dependencies are installed"
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  with_items: "{{dep_packages}}"

- name: Install forever (to run Node.js app)
  npm: name=forever global=yes state=present

- name: Downloading the install script
  get_url: url=https://downloads.lisk.io/lisk/{{env}}/installLisk.sh dest=/home/vagrant

- include: setup-lisk.yml

- name: Reload lisk after config changes
  become_user: vagrant
  command: bash lisk.sh reload
  args:
    chdir: /home/vagrant/lisk-test
