---
# instaling lisk depending on env variable

- name: Running Lisk installation
  become_user: vagrant
  expect:
    command: bash installLisk.sh install -r {{env}}
    responses:
        'install Lisk to': '/home/vagrant'
        'install NTP': 'y'
    timeout: 600
    echo: yes
