# - name: "Installing python req"
#     become: yes
#     apt: pip
#
# - name: "Installing the req pkg"
#     become: yes
#     pip: pexpect

# - expect:
#     become: yes
#     chdir: /home/vagrant
#     command: sh installLisk.sh install -r {{env}}
#     echo: yes
#     responses:
#         path: /home/vagrant
#         ntp: y

- name: "Running Lisk installation script"
  command: sh installLisk.sh install -r {{env}}
  args:
    chdir: "/home/vagrant"
