---
  - name: Add node package
    shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - name: Install nodejs
    apt: name=nodejs force=yes
  - name: Install nodejs essentials
    apt: name=build-essential force=yes
